### ISSUE TITLE
About how to draw the heatmap picture

### ISSUE THREAD

**Issue by ccmCCMfk** [Reagan1311/LOCATE#3]
Thanks for your great work! I got a result KLD=1.252,SIM=0.398,NSS=1.139,But I don't know how to visualize and generate a beautiful heatmap,can you provide some methods?or maybe the python procedures.

**Comment by Reagan1311** [comment]
Hi, the visualization code is provided in the `utils/viz.py`. You can enable the visualization by specifying the argument `args.viz` in training or testing.

**Comment by ccmCCMfk** [comment]
Thank you! Is it ok to just replace "default=False" with "default=True" in parser.add_argument('--viz', action='store_true', default=False)?I'm running it right now.

**Comment by ccmCCMfk** [comment]
Got a result now,for example:
![throw_basketball_basketball_001548](https://github.com/Reagan1311/LOCATE/assets/86772637/6285e4a6-84a6-453c-a7f0-35f9ee6a307e)

**Comment by Reagan1311** [comment]
Good, feel free to modify the code to suite your needs.
