### ISSUE TITLE
About Hand_Object Interaction

### ISSUE THREAD

**Issue by ccmCCMfk** [Reagan1311/LOCATE#4]
Thanks for your great work,I'm thinking that is there a way that we can combine affordance with Hand-Object Interactions? but I'm not quite sure about how to combine affordance with Hand-Object Interactions.

**Comment by Reagan1311** [comment]
Hi, this is a very open question. Affordance can certainly be benefical to the hand-object interaction, as it provides the information about where the interaction is taking place. 

However, exact method depends on the task and problem setting. Feel free to contact me by email to discuss more details.
