### ISSUE TITLE
Different affordance labels with nearly the same output

### ISSUE THREAD

**Issue by EAST-J** [Reagan1311/LOCATE#5]
Thanks for your great work. When I tested some samples from the AGD20K dataset, I found that despite inputting objects with different affordance labels, the outputs are nearly the same. Here is an example (Left with 'HOLD', Right with 'CUT_WITH'): 
![image](https://github.com/Reagan1311/LOCATE/assets/51024280/2bb9eb01-ab2b-49b1-a64a-984b2c0970b9)![image](https://github.com/Reagan1311/LOCATE/assets/51024280/45103bd0-d19f-4a6e-8938-99a8aee0c19c)
Is this a limiation？

**Comment by Reagan1311** [comment]
Yes, this is indeed a limitation, and should be alleviated by enforcing different CAMs for different affordance labels. However, most objects in the AGD20K dataset have duplicate annotations. For example, "hit", "hold" and "swing" all refer to the handle of a tennis racket, making it difficult to add explicit constraints.
